name: Review Assign

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: automatic-reviewer
        uses: hkusu/review-assign-action@v1
        with:
          assignees: ${{ github.actor }} # assign pull request author
          reviewers: reviewers1 # if draft, assigned when draft is released

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Remove "https://" from PR URL
        id: remove_https
        run: |
          PR_URL="${{ github.event.pull_request.html_url }}"
          PR_URL="http://${PR_URL#https://}"          
          echo "::set-output name=pr_url::$PR_URL"

      - name: Set environment variable
        run: echo "PR_CREATED_AT_UTC=${{ github.event.pull_request.created_at }}" >> $GITHUB_ENV

      - name: Convert UTC to KST
        run: |
          UTC_TIME=$PR_CREATED_AT_UTC
          KST_TIME=$(date -u -d "$UTC_TIME 9 hour" "+%Y-%m-%dT%H:%M:%SZ")
          echo "PR_CREATED_AT_KST=$KST_TIME" >> $GITHUB_ENV

      - name: Calculate deadline
        id: deadline
        run: node .github/workflows/scripts/calculatePRDeadline.js
        env:
          PR_CREATED_AT_KST: ${{ env.PR_CREATED_AT_KST }}

      # - name: Run Slack Convert Script
      #   id: slack_convert
      #   run: node .github/workflows/scripts/convertSlackMrkdwn.js
      #   env:
      #     PR_BODY: ${{ github.event.pull_request.body }}

      - name: Send Slack notification When FE PR
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
               "text": "Pull Request 정보",
               "blocks": [
                 {
                   "type": "section",
                   "text": {
                     "type": "mrkdwn",
                     "text": "*Pull Request Title:* <${{ steps.remove_https.outputs.pr_url }}|${{ github.event.pull_request.title }}>"
                   }
                 },
                 {
                   "type": "section",
                   "text": {
                     "type": "mrkdwn",
                     "text": "*리뷰어:* <@Slack-ID>, <@Slack-ID>"
                   }
                 },
                 {
                   "type": "section",
                   "text": {
                     "type": "mrkdwn",
                     "text": "*담당자:* ${{ github.actor }}"
                   }
                 },
                 {
                   "type": "section",
                   "text": {
                     "type": "mrkdwn",
                     "text": "코드리뷰 마감시간: ${{ steps.deadline.outputs.DEADLINE }}"
                   }
                 }
               ]
             }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
# {
#   "type": "section",
#   "text": {
#     "type": "mrkdwn",
#     "text": "*PR 내용:* ${{ steps.slack_convert.outputs.SLACK_MESSAGE }}"
#   }
# },
