name: Create and Upload Apk on Firebase App Distribution

on:
  push:
    branches:
      - 'develop'
    tags:
      - 'v*.*.*'

jobs:
  CI-Develop:
    name: Apk uploading on Firebase App Distribution
    runs-on: ubuntu-latest
    # Tag가 있을 시에만 실행
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      # Step 1 Checkout Repo
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2 Get Version Name
      - name: Extract Version from Tag
        run: echo "VERSION=$(echo ${{ github.ref }} | sed -n 's/^refs\/tags\/v\([0-9]*\.[0-9]*\.[0-9]*\)/\1/p')" >> $GITHUB_ENV

      # Step 3 Npm Cache
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      # Step 4 Setup Node
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Step 5 Install Dependencies npm install
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --ignore-scripts

      # Step 6 Setup JDK
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17

      # Step 7 Setup Ruby
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          working-directory: 'android'
          bundler-cache: true
      # - name: Setup Ruby Root
      #   uses: ruby/setup-ruby@v1
      #   with:
      #     ruby-version: '2.6.10'
      #     working-directory: '.'
      #     bundler-cache: true

      # Step 8 Install bundler & Fastlane
      # - name: Install bundler
      #   run: |
      #     cd android
      #     gem install bundler:2.5.4
      #     bundle config path vendor/bundle
      #     bundle install --jobs 4 --retry 3
      # Step 9 Upload Apk
      - name: Upload Apk to Firebase
        # uses: maierj/fastlane-action@v3.0.0
        # with:
        #   lane: developDistribute
        #   options: '{ "version": ${{ env.VERSION }} }'
        #   subdirectory: 'android'
        #   env: development
        run: |
          cd android && FL_ENV=development bundle exec fastlane developDistribute version:${{ env.VERSION }}

      - name: Commit Git Config Set
        run: |
          git config --local user.email "125953376+slogup-mumu@users.noreply.github.com"
          git config --local user.name "workflow"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Actions Slack Message
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: Github Action Android Develop Apk Uploading # default: 8398a7@action-slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
