name: Deploy workflow on development environment

on:
  push:
    branches:
      - develop
    workflow_dispatch:

jobs:
  deploy:
    environment: development
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14
          node-options: "--max_old_space_size=10240"

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Build
        run: npm run build

      - name: Deploy to AWS S3
        run: aws s3 sync ./dist s3://${{ secrets.AWS_S3_BUCKET }} --delete --acl public-read
        env:
          CI: true
      - name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.DEV_DISTRIBUTION_ID }} --paths "/*"
